#!/usr/bin/env python3
"""
Generate a PRISM DTMC of the chunked-prefill batch scheduler with M unified
request records (PRISM has no arrays/loops, so we emit the records explicitly).

Record 1 is the tagged "victim" (instrumented with gap counters -- NOT a
scheduler privilege); records 2..M are background. This generalizes the
hand-written 3-record model (chunked/scheduler.pm): generating with
M=3, N_SLOTS=2 reproduces it exactly.

Usage:
  python3 gen_scheduler.py --M 8 --out scheduler_big.pm \
        --SP 1 --LP 8 --SO 1 --LO 16 --VP 1 --VO 2 --T 40
Undefined (supply via PRISM -const): N_SLOTS, KV_CAP, CHUNK_BLK, POLICY,
ADM_POLICY, p_arr, p_lp, p_ol_sp, p_ol_lp, T_V.
"""
import argparse

def emit(M, SP, LP, SO, LO, VP, VO, T, GAPMAX, NL, PT, BMAX, PMAX, OMAX):
    L=[]
    def w(s=""): L.append(s)
    recs=list(range(1,M+1))
    bg=list(range(2,M+1))

    w(f"// AUTO-GENERATED by gen_scheduler.py  (M={M} records; record 1 = victim)")
    w("// Chunked-prefill batch scheduler, unified request records. For SMC at scale.")
    w("dtmc")
    w("")
    w(f"const int T = {T};")
    w("const int T_V;        // victim arrival iteration")
    w("const int N_SLOTS;    // batch width (max running)")
    w("const int KV_CAP;     // shared KV pool (blocks)")
    w("const int CHUNK_BLK;  // prefill blocks / iteration")
    w("const int POLICY;     // 0 fcfs-evict(LIFO) ; 1 priority(protect victim)")
    w("const int ADM_POLICY; // 0 FCFS(by arrival) ; 1 SJF(by prompt)")
    w("const double p_arr; const double p_lp; const double p_ol_sp; const double p_ol_lp;")
    w(f"const int SP={SP}; const int LP={LP}; const int SO={SO}; const int LO={LO}; const int VP={VP}; const int VO={VO};")
    w(f"const int SLO_TBT=3; const int K_CASC=2; const int WIN=2; const int GAPMAX={GAPMAX}; const int NL={NL}; const int PT={PT};")
    # stages: 1 VINJECT, 2 ARRIVE, 3 ADMIT, 4..3+M service (record k at stage 3+k), 4+M PREEMPT
    SVC0=3  # service of record k is at stage SVC0+k
    PRE=SVC0+M+1
    w(f"const int VINJECT=1; const int ARRIVE=2; const int ADMIT=3; const int PREEMPT={PRE};")
    w("")
    # helpers
    for i in recs:
        w(f"formula run_{i} = st_{i}=2; formula wait_{i} = st_{i}=1; formula emp_{i} = st_{i}=0;")
    w("formula nrun = " + " + ".join(f"(run_{i}?1:0)" for i in recs) + ";")
    w("formula kv   = " + " + ".join(f"bk_{i}" for i in recs) + ";")
    # admission key and eviction score
    for i in recs:
        w(f"formula key_{i} = ADM_POLICY=1 ? pp_{i} : ad_{i};")
    for i in recs:
        prot = " + (POLICY=1 ? -1000 : 0)" if i==1 else ""
        w(f"formula sc_{i} = (run_{i} & bk_{i}>0) ? (ad_{i}{prot}) : -1;")
    w("formula v_gap1 = min(GAPMAX, v_gap+1);")
    w("")
    w("module worker")
    w("  t : [0..T] init 0;")
    w(f"  stage : [1..{PRE}] init VINJECT;")
    for i in recs:
        w(f"  st_{i}:[0..2] init 0; pp_{i}:[0..{PMAX}] init 0; oo_{i}:[0..{OMAX}] init 0; bk_{i}:[0..{BMAX}] init 0; ad_{i}:[0..T] init 0;")
    w(f"  v_gap:[0..GAPMAX] init 0; v_maxgap:[0..GAPMAX] init 0; v_preempts:[0..3] init 0; preempts:[0..PT] init 0;")
    w(f"  n_lp:[0..NL] init 0; n_lo:[0..NL] init 0; lp_before_v:bool init false; lp_after_v:bool init false; peak_conc:[0..{M}] init 0;")
    w("")
    w("  // terminal")
    w("  [] stage=VINJECT & t=T -> true;")
    w("  // VINJECT: victim -> record 1 (waiting) at T_V")
    w("  [] stage=VINJECT & t<T & t=T_V & emp_1 -> (st_1'=1)&(pp_1'=VP)&(oo_1'=VO)&(ad_1'=t)&(stage'=ARRIVE);")
    w("  [] stage=VINJECT & t<T & !(t=T_V & emp_1) -> (stage'=ARRIVE);")
    w("")
    w("  // ARRIVE: <=1 bg arrival into the lowest-index empty bg record; decoupled lengths")
    for idx,i in enumerate(bg):
        prefix_full = " & ".join(f"!emp_{j}" for j in bg[:idx]) if idx>0 else ""
        guard = f"stage=ARRIVE & emp_{i}" + (f" & {prefix_full}" if prefix_full else "")
        upd_sp_so = f"(st_{i}'=1)&(pp_{i}'=SP)&(oo_{i}'=SO)&(ad_{i}'=t)&(stage'=ADMIT)"
        upd_sp_lo = f"(st_{i}'=1)&(pp_{i}'=SP)&(oo_{i}'=LO)&(ad_{i}'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)"
        upd_lp_so = f"(st_{i}'=1)&(pp_{i}'=LP)&(oo_{i}'=SO)&(ad_{i}'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)"
        upd_lp_lo = f"(st_{i}'=1)&(pp_{i}'=LP)&(oo_{i}'=LO)&(ad_{i}'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)"
        w(f"  [] {guard} ->")
        w(f"      (1-p_arr) : (stage'=ADMIT)")
        w(f"    + p_arr*(1-p_lp)*(1-p_ol_sp) : {upd_sp_so}")
        w(f"    + p_arr*(1-p_lp)*p_ol_sp     : {upd_sp_lo}")
        w(f"    + p_arr*p_lp*(1-p_ol_lp)     : {upd_lp_so}")
        w(f"    + p_arr*p_lp*p_ol_lp         : {upd_lp_lo};")
    allfull=" & ".join(f"!emp_{j}" for j in bg)
    w(f"  [] stage=ARRIVE & {allfull} -> (stage'=ADMIT);")
    w("")
    w("  // ADMIT: FCFS/SJF promote waiting->running while a slot is free (loops); update peak")
    for i in recs:
        lo=" & ".join(f"(!wait_{j} | key_{i}<key_{j})" for j in recs if j<i)
        hi=" & ".join(f"(!wait_{j} | key_{i}<=key_{j})" for j in recs if j>i)
        cond=" & ".join(x for x in [f"stage=ADMIT & wait_{i} & nrun<N_SLOTS", lo, hi] if x)
        w(f"  [] {cond} -> (st_{i}'=2)&(peak_conc'=max(peak_conc,nrun+1));")
    nowait=" & ".join(f"!wait_{i}" for i in recs)
    w(f"  [] stage=ADMIT & (nrun>=N_SLOTS | ({nowait})) -> (stage'={SVC0+1});")
    w("")
    # service stages
    for k in recs:
        st=SVC0+k; nxt=SVC0+k+1 if k<M else PRE
        vic = (k==1)
        gapp = "&(v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1))" if vic else ""
        gap0 = "&(v_gap'=0)" if vic else ""
        w(f"  // service record {k}"+(" (victim: gap counters)" if vic else ""))
        w(f"  [] stage={st} & emp_{k} -> (stage'={nxt});")
        if vic:
            w(f"  [] stage={st} & wait_{k} -> (v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1))&(stage'={nxt});")
        else:
            w(f"  [] stage={st} & wait_{k} -> (stage'={nxt});")
        w(f"  [] stage={st} & run_{k} & pp_{k}>0 -> (bk_{k}'=min({BMAX},bk_{k}+min(pp_{k},CHUNK_BLK)))&(pp_{k}'=pp_{k}-min(pp_{k},CHUNK_BLK)){gapp}&(stage'={nxt});")
        w(f"  [] stage={st} & run_{k} & pp_{k}=0 & oo_{k}>0 -> (oo_{k}'=oo_{k}-1)&(bk_{k}'=(oo_{k}-1=0?0:min({BMAX},bk_{k}+1)))&(st_{k}'=(oo_{k}-1=0?0:2)){gap0}&(stage'={nxt});")
        w(f"  [] stage={st} & run_{k} & pp_{k}=0 & oo_{k}=0 -> (st_{k}'=0)&(bk_{k}'=0)&(stage'={nxt});")
    w("")
    w("  // PREEMPT: evict running->waiting (max score, LIFO / priority) until KV fits (loops)")
    w(f"  [] stage=PREEMPT & kv<=KV_CAP -> (t'=min(T,t+1))&(stage'=VINJECT);")
    for i in recs:
        lo=" & ".join(f"(sc_{i}>sc_{j})" for j in recs if j<i)
        hi=" & ".join(f"(sc_{i}>=sc_{j})" for j in recs if j>i)
        cond=" & ".join(x for x in [f"stage=PREEMPT & kv>KV_CAP & run_{i} & bk_{i}>0", lo, hi] if x)
        pv = "&(v_preempts'=min(3,v_preempts+1))&(v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1))" if i==1 else ""
        w(f"  [] {cond} -> (st_{i}'=1)&(pp_{i}'=bk_{i})&(bk_{i}'=0)&(preempts'=min(PT,preempts+1)){pv};")
    w("endmodule")
    w("")
    w('label "done"        = (t=T);')
    w('label "v_preempted" = (v_preempts>=1);')
    w('label "v_stalled"   = (v_maxgap>=SLO_TBT);')
    w('label "cascade"     = (preempts>=K_CASC);')
    return "\n".join(L)+"\n"

if __name__=="__main__":
    ap=argparse.ArgumentParser()
    ap.add_argument("--M",type=int,default=3)
    ap.add_argument("--SP",type=int,default=1); ap.add_argument("--LP",type=int,default=3)
    ap.add_argument("--SO",type=int,default=1); ap.add_argument("--LO",type=int,default=3)
    ap.add_argument("--VP",type=int,default=1); ap.add_argument("--VO",type=int,default=2)
    ap.add_argument("--T",type=int,default=10)
    ap.add_argument("--out",default="scheduler_gen.pm")
    a=ap.parse_args()
    BMAX=a.LP+a.LO; PMAX=BMAX; OMAX=max(a.LO,a.SO,a.VO)
    GAPMAX=a.T; NL=a.M; PT=2*a.M
    txt=emit(a.M,a.SP,a.LP,a.SO,a.LO,a.VP,a.VO,a.T,GAPMAX,NL,PT,BMAX,PMAX,OMAX)
    open(a.out,"w").write(txt)
    print(f"wrote {a.out}  (M={a.M}, sizes SP{a.SP}/LP{a.LP}/SO{a.SO}/LO{a.LO}, BMAX={BMAX}, T={a.T})")
