P=? [ (true) U<=(224) (iq5_deqs_bl>3) ]

P=? [ (true) U<=(224) (iq5_deqs_bl>3) ]/P=? [ (true) U<=(96) (stage=DEQ&iq5_arrivals<2) ]

P=? [ (G<=(96) (iq5_arrivals<2)) & ((true) U<=(224) (iq5_deqs_bl>3)) ]

P=? [ G<=(96) (iq5_arrivals<2) ]

P=? [ G<=(224) ((time>5)|(iq5_arrivals<2)) ]

P=? [ G<=(224) ((iq5_deqs_bl<4)&((time>5)|(iq5_arrivals<2))) ]

P=? [ G<=(224) (iq5_deqs_bl<4) ]

