// AUTO-GENERATED by gen_scheduler.py  (M=8 records; record 1 = victim)
// Chunked-prefill batch scheduler, unified request records. For SMC at scale.
dtmc

const int T = 40;
const int T_V;        // victim arrival iteration
const int N_SLOTS;    // batch width (max running)
const int KV_CAP;     // shared KV pool (blocks)
const int CHUNK_BLK;  // prefill blocks / iteration
const int POLICY;     // 0 fcfs-evict(LIFO) ; 1 priority(protect victim)
const int ADM_POLICY; // 0 FCFS(by arrival) ; 1 SJF(by prompt)
const double p_arr; const double p_lp; const double p_ol_sp; const double p_ol_lp;
const int SP=1; const int LP=8; const int SO=1; const int LO=16; const int VP=1; const int VO=2;
const int SLO_TBT=3; const int K_CASC=2; const int WIN=2; const int GAPMAX=40; const int NL=8; const int PT=16;
const int VINJECT=1; const int ARRIVE=2; const int ADMIT=3; const int PREEMPT=12;

formula run_1 = st_1=2; formula wait_1 = st_1=1; formula emp_1 = st_1=0;
formula run_2 = st_2=2; formula wait_2 = st_2=1; formula emp_2 = st_2=0;
formula run_3 = st_3=2; formula wait_3 = st_3=1; formula emp_3 = st_3=0;
formula run_4 = st_4=2; formula wait_4 = st_4=1; formula emp_4 = st_4=0;
formula run_5 = st_5=2; formula wait_5 = st_5=1; formula emp_5 = st_5=0;
formula run_6 = st_6=2; formula wait_6 = st_6=1; formula emp_6 = st_6=0;
formula run_7 = st_7=2; formula wait_7 = st_7=1; formula emp_7 = st_7=0;
formula run_8 = st_8=2; formula wait_8 = st_8=1; formula emp_8 = st_8=0;
formula nrun = (run_1?1:0) + (run_2?1:0) + (run_3?1:0) + (run_4?1:0) + (run_5?1:0) + (run_6?1:0) + (run_7?1:0) + (run_8?1:0);
formula kv   = bk_1 + bk_2 + bk_3 + bk_4 + bk_5 + bk_6 + bk_7 + bk_8;
formula key_1 = ADM_POLICY=1 ? pp_1 : ad_1;
formula key_2 = ADM_POLICY=1 ? pp_2 : ad_2;
formula key_3 = ADM_POLICY=1 ? pp_3 : ad_3;
formula key_4 = ADM_POLICY=1 ? pp_4 : ad_4;
formula key_5 = ADM_POLICY=1 ? pp_5 : ad_5;
formula key_6 = ADM_POLICY=1 ? pp_6 : ad_6;
formula key_7 = ADM_POLICY=1 ? pp_7 : ad_7;
formula key_8 = ADM_POLICY=1 ? pp_8 : ad_8;
formula sc_1 = (run_1 & bk_1>0) ? (ad_1 + (POLICY=1 ? -1000 : 0)) : -1;
formula sc_2 = (run_2 & bk_2>0) ? (ad_2) : -1;
formula sc_3 = (run_3 & bk_3>0) ? (ad_3) : -1;
formula sc_4 = (run_4 & bk_4>0) ? (ad_4) : -1;
formula sc_5 = (run_5 & bk_5>0) ? (ad_5) : -1;
formula sc_6 = (run_6 & bk_6>0) ? (ad_6) : -1;
formula sc_7 = (run_7 & bk_7>0) ? (ad_7) : -1;
formula sc_8 = (run_8 & bk_8>0) ? (ad_8) : -1;
formula v_gap1 = min(GAPMAX, v_gap+1);

module worker
  t : [0..T] init 0;
  stage : [1..12] init VINJECT;
  st_1:[0..2] init 0; pp_1:[0..24] init 0; oo_1:[0..16] init 0; bk_1:[0..24] init 0; ad_1:[0..T] init 0;
  st_2:[0..2] init 0; pp_2:[0..24] init 0; oo_2:[0..16] init 0; bk_2:[0..24] init 0; ad_2:[0..T] init 0;
  st_3:[0..2] init 0; pp_3:[0..24] init 0; oo_3:[0..16] init 0; bk_3:[0..24] init 0; ad_3:[0..T] init 0;
  st_4:[0..2] init 0; pp_4:[0..24] init 0; oo_4:[0..16] init 0; bk_4:[0..24] init 0; ad_4:[0..T] init 0;
  st_5:[0..2] init 0; pp_5:[0..24] init 0; oo_5:[0..16] init 0; bk_5:[0..24] init 0; ad_5:[0..T] init 0;
  st_6:[0..2] init 0; pp_6:[0..24] init 0; oo_6:[0..16] init 0; bk_6:[0..24] init 0; ad_6:[0..T] init 0;
  st_7:[0..2] init 0; pp_7:[0..24] init 0; oo_7:[0..16] init 0; bk_7:[0..24] init 0; ad_7:[0..T] init 0;
  st_8:[0..2] init 0; pp_8:[0..24] init 0; oo_8:[0..16] init 0; bk_8:[0..24] init 0; ad_8:[0..T] init 0;
  v_gap:[0..GAPMAX] init 0; v_maxgap:[0..GAPMAX] init 0; v_preempts:[0..3] init 0; preempts:[0..PT] init 0;
  n_lp:[0..NL] init 0; n_lo:[0..NL] init 0; lp_before_v:bool init false; lp_after_v:bool init false; peak_conc:[0..8] init 0;

  // terminal
  [] stage=VINJECT & t=T -> true;
  // VINJECT: victim -> record 1 (waiting) at T_V
  [] stage=VINJECT & t<T & t=T_V & emp_1 -> (st_1'=1)&(pp_1'=VP)&(oo_1'=VO)&(ad_1'=t)&(stage'=ARRIVE);
  [] stage=VINJECT & t<T & !(t=T_V & emp_1) -> (stage'=ARRIVE);

  // ARRIVE: <=1 bg arrival into the lowest-index empty bg record; decoupled lengths
  [] stage=ARRIVE & emp_2 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_2'=1)&(pp_2'=SP)&(oo_2'=SO)&(ad_2'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_2'=1)&(pp_2'=SP)&(oo_2'=LO)&(ad_2'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_2'=1)&(pp_2'=LP)&(oo_2'=SO)&(ad_2'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_2'=1)&(pp_2'=LP)&(oo_2'=LO)&(ad_2'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_3 & !emp_2 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_3'=1)&(pp_3'=SP)&(oo_3'=SO)&(ad_3'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_3'=1)&(pp_3'=SP)&(oo_3'=LO)&(ad_3'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_3'=1)&(pp_3'=LP)&(oo_3'=SO)&(ad_3'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_3'=1)&(pp_3'=LP)&(oo_3'=LO)&(ad_3'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_4 & !emp_2 & !emp_3 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_4'=1)&(pp_4'=SP)&(oo_4'=SO)&(ad_4'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_4'=1)&(pp_4'=SP)&(oo_4'=LO)&(ad_4'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_4'=1)&(pp_4'=LP)&(oo_4'=SO)&(ad_4'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_4'=1)&(pp_4'=LP)&(oo_4'=LO)&(ad_4'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_5 & !emp_2 & !emp_3 & !emp_4 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_5'=1)&(pp_5'=SP)&(oo_5'=SO)&(ad_5'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_5'=1)&(pp_5'=SP)&(oo_5'=LO)&(ad_5'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_5'=1)&(pp_5'=LP)&(oo_5'=SO)&(ad_5'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_5'=1)&(pp_5'=LP)&(oo_5'=LO)&(ad_5'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_6 & !emp_2 & !emp_3 & !emp_4 & !emp_5 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_6'=1)&(pp_6'=SP)&(oo_6'=SO)&(ad_6'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_6'=1)&(pp_6'=SP)&(oo_6'=LO)&(ad_6'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_6'=1)&(pp_6'=LP)&(oo_6'=SO)&(ad_6'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_6'=1)&(pp_6'=LP)&(oo_6'=LO)&(ad_6'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_7 & !emp_2 & !emp_3 & !emp_4 & !emp_5 & !emp_6 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_7'=1)&(pp_7'=SP)&(oo_7'=SO)&(ad_7'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_7'=1)&(pp_7'=SP)&(oo_7'=LO)&(ad_7'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_7'=1)&(pp_7'=LP)&(oo_7'=SO)&(ad_7'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_7'=1)&(pp_7'=LP)&(oo_7'=LO)&(ad_7'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & emp_8 & !emp_2 & !emp_3 & !emp_4 & !emp_5 & !emp_6 & !emp_7 ->
      (1-p_arr) : (stage'=ADMIT)
    + p_arr*(1-p_lp)*(1-p_ol_sp) : (st_8'=1)&(pp_8'=SP)&(oo_8'=SO)&(ad_8'=t)&(stage'=ADMIT)
    + p_arr*(1-p_lp)*p_ol_sp     : (st_8'=1)&(pp_8'=SP)&(oo_8'=LO)&(ad_8'=t)&(n_lo'=min(NL,n_lo+1))&(stage'=ADMIT)
    + p_arr*p_lp*(1-p_ol_lp)     : (st_8'=1)&(pp_8'=LP)&(oo_8'=SO)&(ad_8'=t)&(n_lp'=min(NL,n_lp+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT)
    + p_arr*p_lp*p_ol_lp         : (st_8'=1)&(pp_8'=LP)&(oo_8'=LO)&(ad_8'=t)&(n_lp'=min(NL,n_lp+1))&(n_lo'=min(NL,n_lo+1))&(lp_before_v'=(lp_before_v|t<T_V))&(lp_after_v'=(lp_after_v|t>T_V))&(stage'=ADMIT);
  [] stage=ARRIVE & !emp_2 & !emp_3 & !emp_4 & !emp_5 & !emp_6 & !emp_7 & !emp_8 -> (stage'=ADMIT);

  // ADMIT: FCFS/SJF promote waiting->running while a slot is free (loops); update peak
  [] stage=ADMIT & wait_1 & nrun<N_SLOTS & (!wait_2 | key_1<=key_2) & (!wait_3 | key_1<=key_3) & (!wait_4 | key_1<=key_4) & (!wait_5 | key_1<=key_5) & (!wait_6 | key_1<=key_6) & (!wait_7 | key_1<=key_7) & (!wait_8 | key_1<=key_8) -> (st_1'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_2 & nrun<N_SLOTS & (!wait_1 | key_2<key_1) & (!wait_3 | key_2<=key_3) & (!wait_4 | key_2<=key_4) & (!wait_5 | key_2<=key_5) & (!wait_6 | key_2<=key_6) & (!wait_7 | key_2<=key_7) & (!wait_8 | key_2<=key_8) -> (st_2'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_3 & nrun<N_SLOTS & (!wait_1 | key_3<key_1) & (!wait_2 | key_3<key_2) & (!wait_4 | key_3<=key_4) & (!wait_5 | key_3<=key_5) & (!wait_6 | key_3<=key_6) & (!wait_7 | key_3<=key_7) & (!wait_8 | key_3<=key_8) -> (st_3'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_4 & nrun<N_SLOTS & (!wait_1 | key_4<key_1) & (!wait_2 | key_4<key_2) & (!wait_3 | key_4<key_3) & (!wait_5 | key_4<=key_5) & (!wait_6 | key_4<=key_6) & (!wait_7 | key_4<=key_7) & (!wait_8 | key_4<=key_8) -> (st_4'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_5 & nrun<N_SLOTS & (!wait_1 | key_5<key_1) & (!wait_2 | key_5<key_2) & (!wait_3 | key_5<key_3) & (!wait_4 | key_5<key_4) & (!wait_6 | key_5<=key_6) & (!wait_7 | key_5<=key_7) & (!wait_8 | key_5<=key_8) -> (st_5'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_6 & nrun<N_SLOTS & (!wait_1 | key_6<key_1) & (!wait_2 | key_6<key_2) & (!wait_3 | key_6<key_3) & (!wait_4 | key_6<key_4) & (!wait_5 | key_6<key_5) & (!wait_7 | key_6<=key_7) & (!wait_8 | key_6<=key_8) -> (st_6'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_7 & nrun<N_SLOTS & (!wait_1 | key_7<key_1) & (!wait_2 | key_7<key_2) & (!wait_3 | key_7<key_3) & (!wait_4 | key_7<key_4) & (!wait_5 | key_7<key_5) & (!wait_6 | key_7<key_6) & (!wait_8 | key_7<=key_8) -> (st_7'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & wait_8 & nrun<N_SLOTS & (!wait_1 | key_8<key_1) & (!wait_2 | key_8<key_2) & (!wait_3 | key_8<key_3) & (!wait_4 | key_8<key_4) & (!wait_5 | key_8<key_5) & (!wait_6 | key_8<key_6) & (!wait_7 | key_8<key_7) -> (st_8'=2)&(peak_conc'=max(peak_conc,nrun+1));
  [] stage=ADMIT & (nrun>=N_SLOTS | (!wait_1 & !wait_2 & !wait_3 & !wait_4 & !wait_5 & !wait_6 & !wait_7 & !wait_8)) -> (stage'=4);

  // service record 1 (victim: gap counters)
  [] stage=4 & emp_1 -> (stage'=5);
  [] stage=4 & wait_1 -> (v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1))&(stage'=5);
  [] stage=4 & run_1 & pp_1>0 -> (bk_1'=min(24,bk_1+min(pp_1,CHUNK_BLK)))&(pp_1'=pp_1-min(pp_1,CHUNK_BLK))&(v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1))&(stage'=5);
  [] stage=4 & run_1 & pp_1=0 & oo_1>0 -> (oo_1'=oo_1-1)&(bk_1'=(oo_1-1=0?0:min(24,bk_1+1)))&(st_1'=(oo_1-1=0?0:2))&(v_gap'=0)&(stage'=5);
  [] stage=4 & run_1 & pp_1=0 & oo_1=0 -> (st_1'=0)&(bk_1'=0)&(stage'=5);
  // service record 2
  [] stage=5 & emp_2 -> (stage'=6);
  [] stage=5 & wait_2 -> (stage'=6);
  [] stage=5 & run_2 & pp_2>0 -> (bk_2'=min(24,bk_2+min(pp_2,CHUNK_BLK)))&(pp_2'=pp_2-min(pp_2,CHUNK_BLK))&(stage'=6);
  [] stage=5 & run_2 & pp_2=0 & oo_2>0 -> (oo_2'=oo_2-1)&(bk_2'=(oo_2-1=0?0:min(24,bk_2+1)))&(st_2'=(oo_2-1=0?0:2))&(stage'=6);
  [] stage=5 & run_2 & pp_2=0 & oo_2=0 -> (st_2'=0)&(bk_2'=0)&(stage'=6);
  // service record 3
  [] stage=6 & emp_3 -> (stage'=7);
  [] stage=6 & wait_3 -> (stage'=7);
  [] stage=6 & run_3 & pp_3>0 -> (bk_3'=min(24,bk_3+min(pp_3,CHUNK_BLK)))&(pp_3'=pp_3-min(pp_3,CHUNK_BLK))&(stage'=7);
  [] stage=6 & run_3 & pp_3=0 & oo_3>0 -> (oo_3'=oo_3-1)&(bk_3'=(oo_3-1=0?0:min(24,bk_3+1)))&(st_3'=(oo_3-1=0?0:2))&(stage'=7);
  [] stage=6 & run_3 & pp_3=0 & oo_3=0 -> (st_3'=0)&(bk_3'=0)&(stage'=7);
  // service record 4
  [] stage=7 & emp_4 -> (stage'=8);
  [] stage=7 & wait_4 -> (stage'=8);
  [] stage=7 & run_4 & pp_4>0 -> (bk_4'=min(24,bk_4+min(pp_4,CHUNK_BLK)))&(pp_4'=pp_4-min(pp_4,CHUNK_BLK))&(stage'=8);
  [] stage=7 & run_4 & pp_4=0 & oo_4>0 -> (oo_4'=oo_4-1)&(bk_4'=(oo_4-1=0?0:min(24,bk_4+1)))&(st_4'=(oo_4-1=0?0:2))&(stage'=8);
  [] stage=7 & run_4 & pp_4=0 & oo_4=0 -> (st_4'=0)&(bk_4'=0)&(stage'=8);
  // service record 5
  [] stage=8 & emp_5 -> (stage'=9);
  [] stage=8 & wait_5 -> (stage'=9);
  [] stage=8 & run_5 & pp_5>0 -> (bk_5'=min(24,bk_5+min(pp_5,CHUNK_BLK)))&(pp_5'=pp_5-min(pp_5,CHUNK_BLK))&(stage'=9);
  [] stage=8 & run_5 & pp_5=0 & oo_5>0 -> (oo_5'=oo_5-1)&(bk_5'=(oo_5-1=0?0:min(24,bk_5+1)))&(st_5'=(oo_5-1=0?0:2))&(stage'=9);
  [] stage=8 & run_5 & pp_5=0 & oo_5=0 -> (st_5'=0)&(bk_5'=0)&(stage'=9);
  // service record 6
  [] stage=9 & emp_6 -> (stage'=10);
  [] stage=9 & wait_6 -> (stage'=10);
  [] stage=9 & run_6 & pp_6>0 -> (bk_6'=min(24,bk_6+min(pp_6,CHUNK_BLK)))&(pp_6'=pp_6-min(pp_6,CHUNK_BLK))&(stage'=10);
  [] stage=9 & run_6 & pp_6=0 & oo_6>0 -> (oo_6'=oo_6-1)&(bk_6'=(oo_6-1=0?0:min(24,bk_6+1)))&(st_6'=(oo_6-1=0?0:2))&(stage'=10);
  [] stage=9 & run_6 & pp_6=0 & oo_6=0 -> (st_6'=0)&(bk_6'=0)&(stage'=10);
  // service record 7
  [] stage=10 & emp_7 -> (stage'=11);
  [] stage=10 & wait_7 -> (stage'=11);
  [] stage=10 & run_7 & pp_7>0 -> (bk_7'=min(24,bk_7+min(pp_7,CHUNK_BLK)))&(pp_7'=pp_7-min(pp_7,CHUNK_BLK))&(stage'=11);
  [] stage=10 & run_7 & pp_7=0 & oo_7>0 -> (oo_7'=oo_7-1)&(bk_7'=(oo_7-1=0?0:min(24,bk_7+1)))&(st_7'=(oo_7-1=0?0:2))&(stage'=11);
  [] stage=10 & run_7 & pp_7=0 & oo_7=0 -> (st_7'=0)&(bk_7'=0)&(stage'=11);
  // service record 8
  [] stage=11 & emp_8 -> (stage'=12);
  [] stage=11 & wait_8 -> (stage'=12);
  [] stage=11 & run_8 & pp_8>0 -> (bk_8'=min(24,bk_8+min(pp_8,CHUNK_BLK)))&(pp_8'=pp_8-min(pp_8,CHUNK_BLK))&(stage'=12);
  [] stage=11 & run_8 & pp_8=0 & oo_8>0 -> (oo_8'=oo_8-1)&(bk_8'=(oo_8-1=0?0:min(24,bk_8+1)))&(st_8'=(oo_8-1=0?0:2))&(stage'=12);
  [] stage=11 & run_8 & pp_8=0 & oo_8=0 -> (st_8'=0)&(bk_8'=0)&(stage'=12);

  // PREEMPT: evict running->waiting (max score, LIFO / priority) until KV fits (loops)
  [] stage=PREEMPT & kv<=KV_CAP -> (t'=min(T,t+1))&(stage'=VINJECT);
  [] stage=PREEMPT & kv>KV_CAP & run_1 & bk_1>0 & (sc_1>=sc_2) & (sc_1>=sc_3) & (sc_1>=sc_4) & (sc_1>=sc_5) & (sc_1>=sc_6) & (sc_1>=sc_7) & (sc_1>=sc_8) -> (st_1'=1)&(pp_1'=bk_1)&(bk_1'=0)&(preempts'=min(PT,preempts+1))&(v_preempts'=min(3,v_preempts+1))&(v_gap'=v_gap1)&(v_maxgap'=max(v_maxgap,v_gap1));
  [] stage=PREEMPT & kv>KV_CAP & run_2 & bk_2>0 & (sc_2>sc_1) & (sc_2>=sc_3) & (sc_2>=sc_4) & (sc_2>=sc_5) & (sc_2>=sc_6) & (sc_2>=sc_7) & (sc_2>=sc_8) -> (st_2'=1)&(pp_2'=bk_2)&(bk_2'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_3 & bk_3>0 & (sc_3>sc_1) & (sc_3>sc_2) & (sc_3>=sc_4) & (sc_3>=sc_5) & (sc_3>=sc_6) & (sc_3>=sc_7) & (sc_3>=sc_8) -> (st_3'=1)&(pp_3'=bk_3)&(bk_3'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_4 & bk_4>0 & (sc_4>sc_1) & (sc_4>sc_2) & (sc_4>sc_3) & (sc_4>=sc_5) & (sc_4>=sc_6) & (sc_4>=sc_7) & (sc_4>=sc_8) -> (st_4'=1)&(pp_4'=bk_4)&(bk_4'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_5 & bk_5>0 & (sc_5>sc_1) & (sc_5>sc_2) & (sc_5>sc_3) & (sc_5>sc_4) & (sc_5>=sc_6) & (sc_5>=sc_7) & (sc_5>=sc_8) -> (st_5'=1)&(pp_5'=bk_5)&(bk_5'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_6 & bk_6>0 & (sc_6>sc_1) & (sc_6>sc_2) & (sc_6>sc_3) & (sc_6>sc_4) & (sc_6>sc_5) & (sc_6>=sc_7) & (sc_6>=sc_8) -> (st_6'=1)&(pp_6'=bk_6)&(bk_6'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_7 & bk_7>0 & (sc_7>sc_1) & (sc_7>sc_2) & (sc_7>sc_3) & (sc_7>sc_4) & (sc_7>sc_5) & (sc_7>sc_6) & (sc_7>=sc_8) -> (st_7'=1)&(pp_7'=bk_7)&(bk_7'=0)&(preempts'=min(PT,preempts+1));
  [] stage=PREEMPT & kv>KV_CAP & run_8 & bk_8>0 & (sc_8>sc_1) & (sc_8>sc_2) & (sc_8>sc_3) & (sc_8>sc_4) & (sc_8>sc_5) & (sc_8>sc_6) & (sc_8>sc_7) -> (st_8'=1)&(pp_8'=bk_8)&(bk_8'=0)&(preempts'=min(PT,preempts+1));
endmodule

label "done"        = (t=T);
label "v_preempted" = (v_preempts>=1);
label "v_stalled"   = (v_maxgap>=SLO_TBT);
label "cascade"     = (preempts>=K_CASC);
